/**
 * Auto-generated by scripts/generate-intl-types.mjs.
 * Do not edit manually.
 */

import authSignIn from "../messages/en/auth/sign-in.json";
import common from "../messages/en/common.json";
import invite from "../messages/en/invite.json";
import metadata from "../messages/en/metadata.json";
import platformPage from "../messages/en/platform/page.json";
import platformTeamSettings from "../messages/en/platform/team-settings.json";
import profileSettings from "../messages/en/profile/settings.json";
import tenantAcademicManagement from "../messages/en/tenant/academic-management.json";
import tenantHome from "../messages/en/tenant/home.json";
import tenantLayout from "../messages/en/tenant/layout.json";
import tenantLiveClasses from "../messages/en/tenant/live-classes.json";
import tenantOnboarding from "../messages/en/tenant/onboarding.json";
import tenantPeople from "../messages/en/tenant/people.json";
import tenantProfileSelection from "../messages/en/tenant/profile-selection.json";
import tenantTeam from "../messages/en/tenant/team.json";

export const defaultLocaleMessages = {
  ...authSignIn,
  ...common,
  ...invite,
  ...metadata,
  ...platformPage,
  ...platformTeamSettings,
  ...profileSettings,
  ...tenantAcademicManagement,
  ...tenantHome,
  ...tenantLayout,
  ...tenantLiveClasses,
  ...tenantOnboarding,
  ...tenantPeople,
  ...tenantProfileSelection,
  ...tenantTeam,
} as const;

export type IntlMessagesSchema = typeof defaultLocaleMessages;
export type IntlNamespace = keyof IntlMessagesSchema;
